from __future__ import annotations

CLASS_SEED_DATA = [
    {
        "slug": "classless",
        "name": "Classless",
        "source": "Mork Borg Bare Bones Edition",
        "description": "The default scvm path from the core classless rules.",
        "starting_silver": "2d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d8 (minimum 1)",
        "ability_summary": "Roll 3d6 for each ability and consult the standard table.",
        "equipment_summary": "Standard classless starting equipment, weapon, and armor tables.",
        "notes": "Without classes, characters begin with d2 Omens and use the generic gear tables.",
        "features": [],
    },
    {
        "slug": "fanged-deserter",
        "name": "Fanged Deserter",
        "source": "Mork Borg Bare Bones Edition",
        "description": "A half-feral exile whose teeth are their truest allies.",
        "starting_silver": "2d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d10",
        "ability_summary": "+2 Strength, -1 Agility, -1 Presence. Normal Agility tests are DR14 except defence. Illiterate and incapable of using scrolls.",
        "equipment_summary": "Roll normal class gear and one special item from the class table.",
        "notes": "Bite attack: DR10 to hit, d6 damage, and a 1-2 on d6 gives the enemy a free attack.",
        "features": [
            {"category": "special_item", "roll_label": "1", "name": "Crumpled Monster Mask", "description": "Lesser creatures such as goblins, gnoums, and children test Morale every round while you wear it."},
            {"category": "special_item", "roll_label": "2", "name": "Brown Scimitar of Galgenbeck", "description": "A d6 sword that gives DR10 attack and defence while wielded; wounded enemies may die of sepsis in 10 minutes."},
            {"category": "special_item", "roll_label": "3", "name": "Wizard Teeth", "description": "Before battle roll four teeth; every 6 makes one of your attacks deal maximum damage."},
            {"category": "special_item", "roll_label": "4", "name": "Old Sigurd's Sling", "description": "Deals 2d4 damage with fist-sized rocks."},
            {"category": "special_item", "roll_label": "5", "name": "Ancient Gore-Hound", "description": "A treasure-sniffing hound with bite d6, 10 HP, and berserk hatred for goblins and berserkers."},
            {"category": "special_item", "roll_label": "6", "name": "Shoe of Death's Horse", "description": "Thrown weapon, DR10 to hit, d4 damage, and a 1-in-6 chance to instantly kill a small or medium creature."},
        ],
    },
    {
        "slug": "gutterborn-scum",
        "name": "Gutterborn Scum",
        "source": "Mork Borg Bare Bones Edition",
        "description": "A born survivor of filth, poverty, and criminal luck.",
        "starting_silver": "1d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d6",
        "ability_summary": "-2 Strength. All Presence and Agility tests are DR10 instead of DR12.",
        "equipment_summary": "Roll d6 on the weapon table and d2 on the armor table.",
        "notes": "The first time this class gets better, it rolls another specialty.",
        "features": [
            {"category": "specialty", "roll_label": "1", "name": "Coward's Jab", "description": "When attacking by surprise, test Agility DR10 to automatically hit once with a light one-handed weapon for normal damage +3."},
            {"category": "specialty", "roll_label": "2", "name": "Filthy Fingersmith", "description": "Pick pockets and locks with Agility DR8 and begin with lockpicks."},
            {"category": "specialty", "roll_label": "3", "name": "Abominable Gob Lobber", "description": "Spit d2 times per fight. Presence DR8 blinds and sickens the target for d4 rounds; onlookers may vomit too."},
            {"category": "specialty", "roll_label": "4", "name": "Escaping Fate", "description": "Each time you spend an Omen there is a 50 percent chance it is not lost."},
            {"category": "specialty", "roll_label": "5", "name": "Excretal Stealth", "description": "When hidden in muck, debris, or filth, noticing you requires Presence DR16."},
            {"category": "specialty", "roll_label": "6", "name": "Dodging Death", "description": "If there is any plausible way you survived death, there is a 50 percent chance you return after 10 rounds with d4 HP."},
        ],
    },
    {
        "slug": "esoteric-hermit",
        "name": "Esoteric Hermit",
        "source": "Mork Borg Bare Bones Edition",
        "description": "A cavern mystic dragging occult insight into a ruined world.",
        "starting_silver": "1d6 x 10 silver",
        "omen_die": "d4",
        "hp_formula": "Toughness + d4",
        "ability_summary": "+2 Presence, -2 Strength, and one random sacred or unclean scroll.",
        "equipment_summary": "Ordinary starting equipment plus one random scroll. Roll d4 on the weapon table and d2 on the armor table.",
        "notes": "This class is built around utility, prophecy, and temporary summoned resources.",
        "features": [
            {"category": "special_feature", "roll_label": "1", "name": "Master of Fate", "description": "You know the right way with a Presence DR8 test."},
            {"category": "special_feature", "roll_label": "2", "name": "Book of Boiling Blood", "description": "Once per day force an enemy to resist or summon d2 Berserker-slayers; they may fight for you or turn on you."},
            {"category": "special_feature", "roll_label": "3", "name": "Speaker of Truths", "description": "Twice per day lower the DR of a creature's next test by 4."},
            {"category": "special_feature", "roll_label": "4", "name": "Initiate of the Invisible College", "description": "Once per day summon d2 one-use scrolls that last until sunrise."},
            {"category": "special_feature", "roll_label": "5", "name": "Bard of the Undying", "description": "Music from your harp grants +d4 on reaction rolls."},
            {"category": "special_feature", "roll_label": "6", "name": "Hawk as Weapon", "description": "A loyal hawk scouts and attacks with claws or bite d4, DR10 attack and defence, HP 8."},
        ],
    },
    {
        "slug": "wretched-royalty",
        "name": "Wretched Royalty",
        "source": "Mork Borg Bare Bones Edition",
        "description": "A fallen noble with ruined grandeur and stubborn entitlement.",
        "starting_silver": "4d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d6",
        "ability_summary": "No ability adjustments.",
        "equipment_summary": "Roll d8 on the weapons table and d4 on the armor table, rerolling heavy armor.",
        "notes": "Begins with two class features from the royal relic table.",
        "features": [
            {"category": "royal_relic", "roll_label": "1", "name": "Blade of Your Ancestors", "description": "A magical talking sword dealing d6+1 damage with DR10 attack and defence, but it may betray you if disappointed."},
            {"category": "royal_relic", "roll_label": "2", "name": "Poltroon the Court Jester", "description": "For the first two rounds of combat, you and allies gain +2 on attack and defence."},
            {"category": "royal_relic", "roll_label": "3", "name": "Barbarister the Incredible Horse", "description": "A proud talking horse that may grant +2 to logical Presence tests when persuaded to help."},
            {"category": "royal_relic", "roll_label": "4", "name": "Hamfund the Squire", "description": "Once per combat Eurekia may be drawn for 2d6 damage, but a bad roll kills the squire and loses the sword forever."},
            {"category": "royal_relic", "roll_label": "5", "name": "Snake-Skin Gift", "description": "A silk-wrapped dagger dealing d4 damage, with instant death on a roll of 1 from its deadly poison."},
            {"category": "royal_relic", "roll_label": "6", "name": "Horn of the Schleswig Lords", "description": "Once per day a Presence DR12 test lets one creature automatically succeed at their next non-combat test."},
        ],
    },
    {
        "slug": "heretical-priest",
        "name": "Heretical Priest",
        "source": "Mork Borg Bare Bones Edition",
        "description": "A blasphemous preacher hunted by the official faith.",
        "starting_silver": "3d6 x 10 silver",
        "omen_die": "d4",
        "hp_formula": "Toughness + d8",
        "ability_summary": "+2 Presence, -2 Strength, and may use Powers while wearing medium armor.",
        "equipment_summary": "Roll d8 on the weapons table.",
        "notes": "Blends strong Presence with anti-faith relics and occult support gear.",
        "features": [
            {"category": "holy_item", "roll_label": "1", "name": "Sacred Shepherd's Crook", "description": "A bone-hooked staff dealing 2d4 damage except against faithless humans."},
            {"category": "holy_item", "roll_label": "2", "name": "Stolen Mitre", "description": "Defence is DR10 in combat; outside battle you can become nearly invisible with stealth DR8."},
            {"category": "holy_item", "roll_label": "3", "name": "List of Sins", "description": "Presence DR10 reveals evil creatures in strange light, giving +2 defence against them."},
            {"category": "holy_item", "roll_label": "4", "name": "Blasphemous Nechrubel Bible", "description": "Read once per day for either rapid party healing or demonic hallucinations until sunrise."},
            {"category": "holy_item", "roll_label": "5", "name": "Stones from Thel-Emas", "description": "Cast them to reveal danger in adjacent rooms; Presence DR10 determines whether the stones tell the truth."},
            {"category": "holy_item", "roll_label": "6", "name": "Wrong Jesus Crucifix", "description": "Against undead, goblins, and lesser trolls, check Morale modified by your Presence to make them back away."},
        ],
    },
    {
        "slug": "occult-herbmaster",
        "name": "Occult Herbmaster",
        "source": "Mork Borg Bare Bones Edition",
        "description": "A poison-wise alchemist of glades, mushrooms, and portable laboratories.",
        "starting_silver": "2d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d6",
        "ability_summary": "+2 Toughness, -2 Strength.",
        "equipment_summary": "Roll d6 on the weapons table and d2 on the armor table. Carry a portable laboratory.",
        "notes": "Each day you can brew d4 total doses across two randomly determined decoctions. Unused doses spoil after 24 hours.",
        "features": [
            {"category": "decoction", "roll_label": "1", "name": "Red Poison", "description": "Toughness DR12 or take d10 damage."},
            {"category": "decoction", "roll_label": "2", "name": "Ezumiel's Vapor", "description": "Fail a DR14 test and suffer severe hallucinations for d4 hours."},
            {"category": "decoction", "roll_label": "3", "name": "Southern Frog Stew", "description": "Vomit for d4 hours; fail DR14 and do nothing else."},
            {"category": "decoction", "roll_label": "4", "name": "Elixir Vitalis", "description": "Heals d6 HP and stops infection, but can be habit-forming."},
            {"category": "decoction", "roll_label": "5", "name": "Spider-Owl Soup", "description": "See in darkness and climb walls for 30 minutes."},
            {"category": "decoction", "roll_label": "6", "name": "Fernor's Philtre", "description": "Heals infection and gives +2 on Presence tests for d4 hours."},
            {"category": "decoction", "roll_label": "7", "name": "Hyphos' Enervating Snuff", "description": "Berserk for one fight, attacking twice per round but defending at DR14."},
            {"category": "decoction", "roll_label": "8", "name": "Black Poison", "description": "Toughness DR14 or take d6 damage and be blinded for one hour."},
        ],
    },
    {
        "slug": "cursed-skinwalker",
        "name": "Cursed Skinwalker",
        "source": "MBC_Cursed-Skinwalker",
        "description": "A twice-dead soul fused with a dying beast and trapped between forms.",
        "starting_silver": "2d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d8",
        "ability_summary": "Roll 3d6-2 for Presence. Roll 3d6+1 for Strength and Toughness.",
        "equipment_summary": "Roll d6 on the weapon table and d2 on the armor table. Armor and weapons may become unusable while transformed.",
        "notes": "Changing shape takes one painful round. You carry one beast-form tied to your soul.",
        "features": [
            {"category": "beast_form", "roll_label": "1", "name": "Murder-Plagued Rat", "description": "Agility tests and defence are DR8. Bite d4 carries disease that can turn victims against their nearest ally."},
            {"category": "beast_form", "roll_label": "2", "name": "Flayed and Dripping Wolf", "description": "Attacks are DR10, fangs deal d6, crit on 19-20, and you take -d2 incoming damage."},
            {"category": "beast_form", "roll_label": "3", "name": "Boneskulled Raven", "description": "Defence is DR10, you fly, make two claw attacks for d4, and your skull grants weapon and shield properties."},
            {"category": "beast_form", "roll_label": "4", "name": "Bear from Bergen Chrypt", "description": "Strength and Toughness tests and attacks are DR10, defence is DR14, hide reduces damage by d4, claws and bite deal d8."},
            {"category": "beast_form", "roll_label": "5", "name": "Life-and-Death-Lizard", "description": "Regenerate d4 HP per round, bite d6 or spit acid d4, and scaly skin reduces damage by d2."},
            {"category": "beast_form", "roll_label": "6", "name": "Doomsaying Monkey", "description": "Agility tests and defence are DR10, light armor and weapons remain usable, and your third eye reads unclean scrolls at DR10."},
        ],
    },
    {
        "slug": "dead-gods-prophet",
        "name": "Dead God's Prophet",
        "source": "MBC_Dead_Gods_Prophet",
        "description": "A haunted evangelist whose murdered god still howls through their skull.",
        "starting_silver": "1d6 x 5 silver",
        "omen_die": "d3",
        "hp_formula": "Toughness + d4",
        "ability_summary": "+2 Presence, -2 Toughness. Literate and able to use scrolls, but must pass a Presence DR12 test when encountering them or try to destroy them as false scripture.",
        "equipment_summary": "Roll d4 on the weapon table and d2 on the armor table.",
        "notes": "Begin with two random gifts from the dead god table.",
        "features": [
            {"category": "gift", "roll_label": "1", "name": "Blood Tells", "description": "Before combat, deal d3 damage to yourself to gain +2 to a number of rolls equal to the HP lost."},
            {"category": "gift", "roll_label": "2", "name": "Lord of Nothing", "description": "Your bizarre royal garb grants +2 on rolls to impress the easily fooled."},
            {"category": "gift", "roll_label": "3", "name": "Smell of Decay", "description": "The stink of your god grants +2 on tests to defend against attacks."},
            {"category": "gift", "roll_label": "4", "name": "Incoherent Sophistic Babble", "description": "Targets hearing your litany must pass Presence DR10 or lose their next action."},
            {"category": "gift", "roll_label": "5", "name": "Ichor of Rot", "description": "As a DR12 attack, touch bare skin and force Toughness DR12 or cause frothing spasms for two turns."},
            {"category": "gift", "roll_label": "6", "name": "My Body, a Vessel", "description": "Once per day ask the GM one yes or no question that must be answered truthfully."},
            {"category": "gift", "roll_label": "7", "name": "In Death I Live", "description": "On death, pass Presence DR14 to recover with 1 HP instead of entering the afterlife."},
            {"category": "gift", "roll_label": "8", "name": "Eyes of Holy Fire", "description": "Once per combat make a DR10 attack from burning eyes for d6 damage, then remain blinded for the rest of the fight."},
        ],
    },
    {
        "slug": "pale-one",
        "name": "Pale One",
        "source": "MBC_Pale-one",
        "description": "An alien outsider with shifting gifts and a power that changes with the day.",
        "starting_silver": "d6 x 10 silver",
        "omen_die": "d4",
        "hp_formula": "Toughness + d6",
        "ability_summary": "+1 Agility, +1 Presence, -2 Toughness. Literate only in dead languages. Cannot use scrolls but can use one random Power that changes each dawn or dusk.",
        "equipment_summary": "Roll d6 on the weapon table and d2 on the armor table.",
        "notes": "Designed around weird utility and bodily mutations.",
        "features": [
            {"category": "blessing", "roll_label": "1", "name": "The Stars Were Right", "description": "Roll d4+2 for Omens and say something cryptic every time you spend one."},
            {"category": "blessing", "roll_label": "2", "name": "Membranous Wings", "description": "Fly short distances, but you cannot wear armor."},
            {"category": "blessing", "roll_label": "3", "name": "Uncommon Clay", "description": "You can live off soil, normal food makes you sick, and you smell like mushrooms."},
            {"category": "blessing", "roll_label": "4", "name": "Mana from Somewhere", "description": "Spend a Power use to create food for d6 people."},
            {"category": "blessing", "roll_label": "5", "name": "Digitigrade Limbs", "description": "Escape bindings, fit through tiny spaces, and reduce DR by 4 on flexibility tests."},
            {"category": "blessing", "roll_label": "6", "name": "Too Many Eyes", "description": "You cannot be surprised and can spend a Power use to leave behind a spying eye."},
        ],
    },
    {
        "slug": "forlorn-philosopher",
        "name": "Forlorn Philosopher",
        "source": "MORK BORG Forlorn Philosopher",
        "description": "A cold, broken thinker chasing reason through an unreasoning apocalypse.",
        "starting_silver": "d6 x 10 silver",
        "omen_die": "d4",
        "hp_formula": "Toughness + d4",
        "ability_summary": "+2 Presence, -2 Strength. Presence DR14 can tear through deceptions and delusions.",
        "equipment_summary": "Roll d6 on the weapon table and d2 on the armor table. Begin with one Tablet of Ochre Obscurity and one special asset.",
        "notes": "This class leans heavily on peculiar relics and mental overreach.",
        "features": [
            {"category": "philosopher_asset", "roll_label": "1", "name": "Thorns of Comprehension", "description": "Take escalating self-damage to perceive all, gain -4 DR on your next test, and ignore the next two attacks against you."},
            {"category": "philosopher_asset", "roll_label": "2", "name": "Hegelian Owl", "description": "A reluctant owl assistant that can fetch items, attack, and find traps after a Presence DR12 test."},
            {"category": "philosopher_asset", "roll_label": "3", "name": "Prism of Ambiguity", "description": "With light and Presence DR10, heal up to two creatures for d6 and improve one target's DRs by 2 for an hour; failure harms them instead."},
            {"category": "philosopher_asset", "roll_label": "4", "name": "Flute of Tosk", "description": "Once per combat, echo fatal damage from a slain creature onto a random nearby enemy."},
            {"category": "philosopher_asset", "roll_label": "5", "name": "Sash of the Stylite", "description": "You ignore hunger and can heal by drinking water alone while resting, but prolonged use causes collapse."},
            {"category": "philosopher_asset", "roll_label": "6", "name": "Marked by Obscurity", "description": "A shifting Tablet of Ochre Obscurity is tattooed into your flesh and can be used once per day with automatic success."},
        ],
    },
    {
        "slug": "dire-hunter",
        "name": "Dire Hunter",
        "source": "Dire Hunter",
        "description": "A relentless wilderness hunter wearing the remains of the beast that once stalked them.",
        "starting_silver": "1d6 x 10 silver",
        "omen_die": "d2",
        "hp_formula": "Toughness + d6",
        "ability_summary": "+1 Agility, +1 Presence, -2 Strength. Illiterate and raised in seclusion.",
        "equipment_summary": "Roll d10 on the weapon table, start with a bow, and roll d2 on the armor table.",
        "notes": "Carry an arcane quiver. Each day you can channel two random arcane effects and imbue a total of d4 arrows or bolts; unused charges fade after 24 hours.",
        "features": [
            {"category": "mantle", "roll_label": "1", "name": "Hooded Cobra Mantle", "description": "A hooded cobra draped over your head and running down your spine."},
            {"category": "mantle", "roll_label": "2", "name": "Troll-Horn Mantle", "description": "Gnarled troll horns rest over your shoulders like a crown."},
            {"category": "mantle", "roll_label": "3", "name": "Blood-Scarred Avian Skull", "description": "A bird skull and tattered feathers edge your cloak."},
            {"category": "mantle", "roll_label": "4", "name": "Necklace of Teeth and Bone", "description": "Collected from everything that ever tried to harm you."},
            {"category": "mantle", "roll_label": "5", "name": "Boots of Warning", "description": "Made from another creature, leaving footprints that warn the world."},
            {"category": "mantle", "roll_label": "6", "name": "Mosaic of Hunt Scars", "description": "A body-wide record of your eternal hunt."},
            {"category": "arcane_effect", "roll_label": "1", "name": "Riftbolt", "description": "You disappear when the arrow is loosed and materialize at the point of impact."},
            {"category": "arcane_effect", "roll_label": "2", "name": "Ashenthorn", "description": "Any damage the target deals is halved for d6 rounds."},
            {"category": "arcane_effect", "roll_label": "3", "name": "Red-Nova", "description": "Embers shower the target for +d4 damage and scorch anything else in melee range."},
            {"category": "arcane_effect", "roll_label": "4", "name": "The Bergen Shadow", "description": "A non-lethal arrow renders the target unconscious for d6x10 minutes or until attacked."},
            {"category": "arcane_effect", "roll_label": "5", "name": "Bloodletter", "description": "For d6 rounds, any damage dealt to the target is increased by 2."},
            {"category": "arcane_effect", "roll_label": "6", "name": "Eclipse", "description": "The target sees only five feet ahead for d6 rounds as madness floods their mind."},
            {"category": "arcane_effect", "roll_label": "7", "name": "Scaledlance", "description": "The arrow takes on a serpent form and animates to attack its target."},
            {"category": "arcane_effect", "roll_label": "8", "name": "Sin-Seeker", "description": "This attack always hits, tracing the target's ephemeral guilt through the Dying World."},
        ],
    },
]
